# Generated by Django 2.2.2 on 2019-07-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_buynow_delieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='buynow',
            name='delieve',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Orderdetail'),
        ),
    ]
