# Generated by Django 2.2.2 on 2019-07-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_buynow_delieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliever',
            name='item',
            field=models.ManyToManyField(to='user.data'),
        ),
    ]
